source "http://rubygems.org"

gem 'feedbacks', path: '../../'
gem 'rails', '~> 3.2.0'
gem 'sqlite3'

gem "jquery-rails"
gem "jquery-ui-rails", :group => :assets


group :development, :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
end